In [1]:
print ("wesley")

wesley


In [2]:
var = 3.141592

In [3]:
var


3.141592

In [4]:
type(var)

float

In [5]:
int(var)

3

In [6]:
type(int(var))

int

In [1]:
#identacão
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


In [1]:
import numpy as np

In [16]:
km = np.loadtxt('carros-km.txt')


In [17]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [3]:
an = np.loadtxt('carros-anos.txt')

NameError: name 'np' is not defined

In [15]:
an

array([2003., 1991., 1990., 2019., 2006., 2012., 2019., 2009., 2010.,
       2011., 2002., 2007., 2001., 2019., 2009., 2016., 2012., 2019.,
       2016., 2017., 2002., 2019., 1994., 1991., 2019., 2019., 2016.,
       2019., 2002., 1991., 1997., 1995., 2018., 1991., 2014., 1995.,
       2019., 2019., 2009., 2019., 2013., 2003., 2019., 2002., 2019.,
       2002., 2004., 2001., 2019., 2003., 2009., 2006., 2000., 2006.,
       2010., 1994., 2007., 2019., 2019., 2019., 2019., 2019., 2017.,
       2011., 2001., 1996., 2019., 1994., 2019., 2007., 1994., 2007.,
       1997., 2006., 2013., 1994., 2008., 2008., 2019., 2019., 1999.,
       2007., 1993., 1995., 2019., 2019., 2016., 2011., 2019., 2002.,
       2013., 2017., 2016., 2008., 2018., 2003., 2003., 2004., 2010.,
       2019., 2006., 2001., 2019., 2015., 2018., 2017., 1992., 2001.,
       1993., 1995., 2003., 2014., 2008., 2013., 2019., 2017., 2019.,
       2019., 2006., 2015., 2007., 2005., 2017., 1998., 2019., 1999.,
       2019., 2009.,

In [12]:
nm = open("carros-nomes.txt", "r")

In [13]:
nm.read()

'Jetta Variant\nPassat\nCrossfox\nDS5\nAston Martin DB4\nPalio Weekend\nA5\nSerie 3 Cabrio\nDodge Jorney\nCarens\nFord Edge\nCourier\nS-18\nJ5\nF-Type Coupe\nRAM\nSerie 1\nA3\nXC90\nRS 3 Sportback\nPajero Sport\nSerie 1 M\nLamborghini Obvious\nEffa Hafei Picape Bau\nLamborghini Murcielago\nUp!\nFiesta Rocam Sedan\nSandero Stepway\nCayman S\nV40\nClasse SLS AMG\nGol G4\nLinea\nFord F100\nJ2\nAston Martin DBS\nPajero TR4\nPolo Sedan\nCalifornia\nS60\nTucson\nHB20\nOptima\nLogan\nRange Rover Vogue\nSonata\nFord New Fiesta Sedan\nSerie 5 Gran Turismo\nCR-V\nFord EcoSport\nVersa\nClasse E\nCarnival\nAston Martin V8 Vantage Roadster\nHoggar\nA1\nAston Martin DB7 Vantage\nCLA\nAccord\nEXTRA 103EX\nSorento\nTiggo\nNew Fiesta Hatch\nJeep Renegade\nLamborghini Ankonian\nSpace Cross\nTouareg\nClasse M\nLancer Evolution X\nKangoo Express\nSW4\nCadillac ELR\nDoblo\nLamborghini Egoista\nFit\nC5\nCeler Hatch\nHB20S\nCielo Hatch\nLivina\nDucato\nMarch\nCadillac XTS sedan\nLamborghini Centenario\nHilux

In [14]:
nm

<_io.TextIOWrapper name='carros-nomes.txt' mode='r' encoding='cp1252'>

In [19]:
qi = 89.000
aca = 2017
ana = 2023

In [20]:
km_media = qi / (ana - aca)

In [21]:
km_media

14.833333333333334

In [22]:
km_total = km_media * 6

In [23]:
km_total

89.0

In [26]:
km_mes = km_media / 12

In [27]:
km_mes

1.2361111111111112

In [41]:
import numpy as np
au = np.loadtxt('carros-anos.txt')

In [42]:
au

array([2003., 1991., 1990., 2019., 2006., 2012., 2019., 2009., 2010.,
       2011., 2002., 2007., 2001., 2019., 2009., 2016., 2012., 2019.,
       2016., 2017., 2002., 2019., 1994., 1991., 2019., 2019., 2016.,
       2019., 2002., 1991., 1997., 1995., 2018., 1991., 2014., 1995.,
       2019., 2019., 2009., 2019., 2013., 2003., 2019., 2002., 2019.,
       2002., 2004., 2001., 2019., 2003., 2009., 2006., 2000., 2006.,
       2010., 1994., 2007., 2019., 2019., 2019., 2019., 2019., 2017.,
       2011., 2001., 1996., 2019., 1994., 2019., 2007., 1994., 2007.,
       1997., 2006., 2013., 1994., 2008., 2008., 2019., 2019., 1999.,
       2007., 1993., 1995., 2019., 2019., 2016., 2011., 2019., 2002.,
       2013., 2017., 2016., 2008., 2018., 2003., 2003., 2004., 2010.,
       2019., 2006., 2001., 2019., 2015., 2018., 2017., 1992., 2001.,
       1993., 1995., 2003., 2014., 2008., 2013., 2019., 2017., 2019.,
       2019., 2006., 2015., 2007., 2005., 2017., 1998., 2019., 1999.,
       2019., 2009.,

In [9]:
len(au)

258

In [48]:
au [3:16]

array([2019., 2006., 2012., 2019., 2009., 2010., 2011., 2002., 2007.,
       2001., 2019., 2009., 2016.])

In [47]:
print(au[-1])
print(au[0])





1992.0
2003.0
